version: '3.8'

services:
  web:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "5001:8080"
    networks:
      - animal-draw-game-network

networks:
  animal-draw-game-network:
    external: true